---
- hosts: 172.31.38.125
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install apache2 webserver 
    apt: 
      name: apache2
      state: present
  - name: i want to copy static file into node side 
    copy:
       src: mytestfile
       dest: /home/ubuntu/

